### ISSUE TITLE
Game will not load after update mod

### ISSUE THREAD

**Issue by SAIANBY** [celsiusqc/totw_modded_mod#14]
Minecraft - 1.19.2
Forge version - 43.3.38
Mod version - totw_modded-forge-1.0.3-1.19.2

[latest.log](https://github.com/celsiusqc/totw_modded_mod/files/14529845/latest.log)

**Comment by QianFuv** [comment]
I have encountered the same issue, but currently, the version causing this error is no longer available on CurseForge. This is quite strange.

**Comment by zachsai** [comment]
Yes, I archived the version until I fix it

**Comment by zachsai** [comment]
Fix coming today

**Comment by QianFuv** [comment]
It seems like this issue has not been fully resolved yet.
```
[193月2024 09:50:11.404] [main/ERROR] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Locator {mods folder locator at D:\QFproject\Miracles-Journey-Pack\.minecraft\versions\Miracles Journey\mods} found an invalid mod file net.minecraftforge.fml.loading.moddiscovery.ModFileInfo@7fd99443
net.minecraftforge.fml.loading.moddiscovery.InvalidModFileException: Illegal version number specified forge-1.19.2-1.0.4 (totw_modded-forge-1.19.2-1.0.4.jar)
	at net.minecraftforge.fml.loading.moddiscovery.ModInfo.<init>(ModInfo.java:106) ~[fmlloader-1.19.2-43.3.8.jar%23150!/:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.lambda$new$2(ModFileInfo.java:69) ~[fmlloader-1.19.2-43.3.8.jar%23150!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.<init>(ModFileInfo.java:70) ~[fmlloader-1.19.2-43.3.8.jar%23150!/:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.modsTomlParser(ModFileParser.java:47) ~[fmlloader-1.19.2-43.3.8.jar%23150!/:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.readModList(ModFileParser.java:31) ~[fmlloader-1.19.2-43.3.8.jar%23150!/:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(ModFile.java:79) ~[fmlloader-1.19.2-43.3.8.jar%23150!/:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(ModFile.java:68) ~[fmlloader-1.19.2-43.3.8.jar%23150!/:?]
	at net.minecraftforge.fml.loading.moddiscovery.AbstractModProvider.createMod(AbstractModProvider.java:52) ~[fmlloader-1.19.2-43.3.8.jar%23150!/:?]
	at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.lambda$scanMods$0(AbstractJarFileModLocator.java:19) ~[fmlloader-1.19.2-43.3.8.jar%23150!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.scanMods(AbstractJarFileModLocator.java:19) ~[fmlloader-1.19.2-43.3.8.jar%23150!/:?]
	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:74) ~[fmlloader-1.19.2-43.3.8.jar%23150!/:?]
	at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:166) ~[fmlloader-1.19.2-43.3.8.jar%23150!/:1.0]
	at net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86) ~[fmlloader-1.19.2-43.3.8.jar%23150!/:1.0]
	at cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112) ~[modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100) ~[modlauncher-10.0.8.jar%23137!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) [?:?]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) [?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) [?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) [?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) [?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) [?:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:87) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23137!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
```
